# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- none

variables:
  solution: 'AdventureWorks10.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

stages:
- stage: CI
  displayName: Build
  jobs: 
  - job: Build
    pool:
      vmImage: 'windows-latest'
    steps:
    - task: NuGetToolInstaller@1
      inputs:
        versionSpec: '7.0.1'
    
    - task: NuGetCommand@2
      inputs:
        restoreSolution: '$(solution)'

    - task: VSBuild@1
      inputs:
        solution: '$(solution)'
        msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactStagingDirectory)"'
        platform: '$(buildPlatform)'
        configuration: '$(buildConfiguration)'
        msbuildArchitecture: 'x64'

    - task: VSTest@2
      inputs:
        platform: '$(buildPlatform)'
        configuration: '$(buildConfiguration)'
  
    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: '$(Build.BinariesDirectory)'
        includeRootFolder: true
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
        replaceExistingArchive: true
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'

- stage: Deploy
  displayName: Deploy to WebApp
  jobs:
  - job: Deploy
    pool:
      vmImage: windows-latest
    steps:
    #download artifacts
    - download: AdvWorks10-ci
  
    # Deploy App Service Plan + App Service using Bicep
    - task: AzureResourceManagerTemplateDeployment@3
      displayName: Deploy App Service Plan Bicep
      inputs:
        deploymentScope: 'Resource Group'
        azureResourceManagerConnection: '$(azureserviceconnection)'
        subscriptionId: '$(subscriptionid)'
        action: 'Create Or Update Resource Group'
        resourceGroupName: '$(resource-group)'
        location: '$(location)'
        templateLocation: 'Linked artifact'
        csmFile: '$(Pipeline.Workspace)/eshoponweb-ci/Bicep/$(templateFile)'
        overrideParameters: '-webAppName $(webappname) -location $(location)'
        deploymentMode: 'Incremental'
        deploymentOutputs: 'asp-json'
    
    #Publish Website to Azure WebApp
    - task: AzureRmWebAppDeployment@4
      displayName: Publish Website to WebApp
      inputs:
        ConnectionType: 'AzureRM'
        azureSubscription: '$(azureserviceconnection)'
        appType: 'webApp'
        WebAppName: '$(webappname)'
        packageForLinux: '$(Pipeline.Workspace)/eshoponweb-ci/Website/Web.zip'